name: "Chromatic"
on:
  pull_request:
    types: [opened,edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build
    - uses: chromaui/action@v1
      with:
        projectToken: e3qe8yb2sx
        token: ${{ secrets.GITHUB_TOKEN }}
